
GET http://localhost:3003/api/blogs
###

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYxMmEzM2RhYzc3ZDkyMjM4ODIwMTAyOSIsImlhdCI6MTYzMDQ5Njg3Mn0.b561lv1hIGNWtOCnFneJg0TZZ_-B_suG0FsN2UDn51g

{
    "title": "Fixed bugs",
    "author": "Pau Sembla",
    "url": "http://dsoifhds.com",
    "likes": 100
}
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYxMmEzM2RhYzc3ZDkyMjM4ODIwMTAyOSIsImlhdCI6MTYzMDQ5Njg3Mn0.b561lv1hIGNWtOCnFneJg0TZZ_-B_suG0FsN2UDn51g

{
    "title": "Post blog",
    "author": "http://dsoifhds.com",
    "url": "dfdsf"
}
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eYJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjEiLCJpZCI6IjYxMmEyMGUxZDVmODg1MGJkZmZiYzQ5YiIsImlhdCI6MTYzMDE2NTgxMX0.Zv_eGFeBHc9pWrw_YmMOYI30thoI5eVl50XuwOpMvqo

{
    "title": "Zombie",
    "author": "Cranberries",
    "url": "lsdkfhdslkd",
    "likes": 120,

}

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYxMmEzM2RhYzc3ZDkyMjM4ODIwMTAyOSIsImlhdCI6MTYzMDE2Mjk4OH0.881-1YNSxDEGCqH-aosRT2YUrX4VAC50paxpmfzSI_s

{
    "title": "You are enough",
    "author": "Zox",
    "url": "dsdfiodfmri",
    "likes": 40
}
###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYxMmEzM2RhYzc3ZDkyMjM4ODIwMTAyOSIsImlhdCI6MTYzMDE2Mjk4OH0.881-1YNSxDEGCqH-aosRT2YUrX4VAC50paxpmfzSI_s

{
    "title": "Blog of",
    "author": "Franco Coulson",
    "url": "eriotqejrv",
    "likes": 120
}
###

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "url": "sdfmdlskfsdlf",
    "likes": 100
}
###
DELETE http://localhost:3003/api/blogs/612f6fa157a18d6b861d2821
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYxMmEzM2RhYzc3ZDkyMjM4ODIwMTAyOSIsImlhdCI6MTYzMDQ5Njg3Mn0.b561lv1hIGNWtOCnFneJg0TZZ_-B_suG0FsN2UDn51g

###
PUT http://localhost:3003/api/blogs/612f6fa157a18d6b861d2821
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldjIiLCJpZCI6IjYxMmEzM2RhYzc3ZDkyMjM4ODIwMTAyOSIsImlhdCI6MTYzMDQ5Njg3Mn0.b561lv1hIGNWtOCnFneJg0TZZ_-B_suG0FsN2UDn51g

{
    "title": "Updated blog",
    "author": "Pau Sembla",
    "url": "ioufref",
    "likes": 120
}
